config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :enrollments do
    get :my_students, on: :collection
  end
  root 'home#index'
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons, except: [:index] do
      resources :comments, except: [:index]
      # put :sort
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: %i[new create]
  end
  resources :users, only: %i[index edit show update]
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
  get 'privacy_policy', to: 'home#privacy_policy'
  resources :youtube, only: :show

  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end
  # get 'charts/users_per_day', to: 'charts#users_per_day'
  # get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  # get 'charts/course_popularity', to: 'charts#course_popularity'
  # get 'charts/money_makers', to: 'charts#money_makers'
end

app/views/layouts/shared/_flash.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'} alert-dismissible fade show", :role => "alert"}
      = content_tag :div, msg, :id => "flash_#{name}"
      %button{"aria-hidden" => "true", "data-bs-dismiss" => "alert", :type => "button", :class => "btn-close"}

app/views/layouts/shared/_footer.html.haml
%hr
%footer.footer
  .container
    .row
      .col-md-4
        = link_to 'Teach on Corsego', new_course_path
        .row
        Corsego for business
        .row
        About us
      .col-md-4
        = link_to 'Privacy policy', privacy_policy_path
        .row
        Terms and conditions
        .row
        Careers
        .row
        Help and Support
        .row
        Blog
      .col-md-4
        Copyright
        ©
        = Time.now.year
        Corsego Sp. z o.o.
        .row
        .fa.fa-envelope
        = mail_to 'example@example.com'
        .row
%br

app/views/layouts/shared/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.purple-background.sticky-md-top
  %a.navbar-brand{:href => "/"}
    = image_tag 'logo-white.png', size: '30x30', alt: "logo"
    /.fa.fa-graduation-cap
    CourseGo Sample
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse.justify-content-md-around
    - if current_user
      %ul.navbar-nav.mr-auto
        %li.nav-item
          = link_to root_path, class: class_names('nav-link', { active: current_page?(root_path) }) do
            .fa.fa-home
            Home
        %li.nav-item
          = link_to courses_path, class: class_names('nav-link', { active: current_page?(courses_path) }) do
            .fa.fa-graduation-cap
            Courses

        .d-flex.flex-row.align-items-center.flex-wrap
          = render 'layouts/shared/nav_search'

      %ul.navbar-nav.mr-auto
        - if current_user.has_role?(:student)
          = render 'layouts/shared/dropdown/student'

        - if current_user.has_role?(:teacher)
          = render 'layouts/shared/dropdown/teacher'

        - if current_user.has_role?(:admin)
          = render 'layouts/shared/dropdown/admin'

      %ul.navbar-nav
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            - if current_user.image?
              = image_tag current_user.image, size: '30x30', alt: "#{current_user.email}", class: 'rounded-circle'
            - else
              .fa.fa-user
            %b= current_user.username
          .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
            = link_to user_path(current_user), class: "dropdown-item" do
              .fa.fa-user
              %b My profile
            = link_to edit_user_registration_path, class: "dropdown-item" do
              .fa.fa-cog
              %b Account settings
            = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
              .fa.fa-sign-out-alt
              %b Sign out
    - else
      %ul.navbar-nav
      %ul.navbar-nav
        %li.nav-item
          = link_to 'Sign Up', new_user_registration_path,
          class: class_names('nav-link', { active: current_page?(new_user_registration_path) })
        %li.nav-item
          = link_to 'Log In', new_user_session_path,
          class: class_names('nav-link', { active: current_page?(new_user_session_path) })
        %li.nav-item
        = link_to user_google_oauth2_omniauth_authorize_path, method: :post, class: 'nav-link' do
          .fab.fa-google
        = link_to user_github_omniauth_authorize_path, method: :post, class: 'nav-link' do
          .fab.fa-github
        = link_to user_facebook_omniauth_authorize_path, method: :post, class: 'nav-link' do
          .fab.fa-facebook

app/views/layouts/shared/_nav_search.html.haml
= search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
  .input-group
    = f.search_field :title_cont, class: 'form-control-sm', style: 'float: left; width: 150px; ', placeholder: 'Find a course', :autocomplete => :off
    %span.input-group-append
      %button.btn.btn-primary.btn-sm{:type => "submit"}
        %span.fa.fa-search{"aria-hidden" => "true"}