config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :enrollments do
    get :my_students, on: :collection
  end
  root 'home#index'
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons, except: [:index] do
      resources :comments, except: [:index]
      # put :sort
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: %i[new create]
  end
  resources :users, only: %i[index edit show update]
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
  get 'privacy_policy', to: 'home#privacy_policy'
  resources :youtube, only: :show

  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end
  # get 'charts/users_per_day', to: 'charts#users_per_day'
  # get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  # get 'charts/course_popularity', to: 'charts#course_popularity'
  # get 'charts/money_makers', to: 'charts#money_makers'
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index privacy_policy]
  def index
    @latest_good_reviews = Enrollment.reviewed.latest_good_reviews # 2 scopes
    @latest = Course.latest.published.approved
    @top_rated = Course.top_rated.published.approved
    @popular = Course.popular.published.approved
    @purchased_courses = Course.joins(:enrollments).where(enrollments: { user: current_user }).order(created_at: :desc).limit(3)
  end

  def activity
    if current_user.has_role?(:admin)
      # @activities = PublicActivity::Activity.all
      @pagy, @activities = pagy(PublicActivity::Activity.all.order(created_at: :desc))
    else
      redirect_to root_path, alert: "You are not authorized to access this page"
    end
  end

  def analytics
    if current_user.has_role?(:admin)
      # @users = User.all
      # @enrollments = Enrollment.all
      # @courses = Course.all
    else
      redirect_to root_path, alert: "You are not authorized to access this page"
    end
  end

  def privacy_policy
  end
end

app/views/home/activity.html.haml
%h3
  .text-center
    Activity
    .badge.bg-info
      = @activities.count
%p

%ul.list-group
  - @activities.each do |activity|
    %li.list-group-item
      -# = activity.id
      .badge.rounded-pill.bg-info
        = activity.created_at.strftime('%d-%m-%Y %H:%m')
      (#{time_ago_in_words(activity.created_at)})
      = model_label(activity.trackable_type)
      -# = activity.trackable_id
      - if activity.trackable_type == 'Lesson'
        - if Lesson.where(id: activity.trackable_id).present?
          = link_to activity.trackable, course_lesson_path(activity.trackable.course, activity.trackable)
        - else
          Lesson was deleted
      - elsif activity.trackable_type == "Comment"
        - if Comment.where(id: activity.trackable_id).any?
          = link_to activity.trackable.content, course_lesson_path(activity.trackable.lesson.course, activity.trackable.lesson)
        - else
          Comment was deleted
      - else
        = link_to activity.trackable, activity.trackable
      = crud_label(activity.key.match(/\.(.*)/)[1])
      /= activity.key.match(/\.(.*)/)[1] - course. опускается, а в метод приходит только экшен
      -# = activity.parameters
      -# = activity.owner

      by
      = link_to activity.owner, user_path(activity.owner)
      - if activity.parameters.any?
        = activity.parameters

!= pagy_bootstrap_nav(@pagy)
%br

app/views/home/analytics.html.haml
%h4.text-center
  New users per day
-# = line_chart @users.group_by_day(:created_at).count
= line_chart charts_users_per_day_path

%h4.text-center
  New enrollments per day
-# = column_chart @enrollments.group_by_day(:created_at).count
= column_chart charts_enrollments_per_day_path

%h4.text-center
  Most enrolled courses

/= pie_chart @courses.group(:enrollments_count).count
/= pie_chart @enrollments.joins(:course).group(:'courses.title').count
-# = bar_chart @enrollments.joins(:course).group(:'courses.title').count
= bar_chart charts_course_popularity_path

%h4.text-center
  Most paid courses
= bar_chart charts_money_makers_path

app/views/home/index.html.haml
.p-5.mb-4.bg-light.border.rounded-3.shadow-sm
  .display-4
    What do you want to learn today?

  .p-4

  - if current_user
    .p-3
    = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
      .input-group
        = f.search_field :title_cont, class: 'form-control-lg', style: 'float: left; width: 200px; ', placeholder: 'Find a course', :autocomplete => :off
        %span.input-group-append
          %button.btn.btn-primary.btn-lg{:type => "submit"}
            %span.fa.fa-search{"aria-hidden" => "true"}
    .p-2
  - else
    %h3 Join to access all the courses
    .p-2
    = link_to 'Register', new_user_registration_path, class: 'btn btn-custom-purple btn-lg'
    = link_to 'Login', new_user_session_path, class: 'btn btn-custom-purple btn-lg'
    .row.mt-1
    = link_to user_google_oauth2_omniauth_authorize_path, method: :post, class: 'btn btn-danger btn-lg mr-1' do
      Continue with
      .fab.fa-google
    .row.mt-1
    = link_to user_github_omniauth_authorize_path, method: :post, class: 'btn btn-dark btn-lg mr-1' do
      Continue with
      .fab.fa-github
    .row.mt-1
    = link_to user_facebook_omniauth_authorize_path, method: :post, class: 'btn btn-primary btn-lg mr-1' do
      Continue with
      .fab.fa-facebook
.card-group.shadow-sm
  .card.card-body
    %h1
      .fa.fa-graduation-cap
    = Course.count
    online courses
    .row
    Explore a variety of fresh topics
  .card.card-body
    %h1
      .fa.fa-chalkboard-teacher
      /.fa.fa-brain
    = Course.distinct.count(:user_id)
    expert instructors
    .row
    Find the right instructor for you
  .card.card-body
    %h1
      .fa.fa-user-graduate
    = User.count
    active learners
    .row
    Join the knowledge sharing community
  .card.card-body
    %h1
      .fa.fa-infinity
    Lifetime access
    .row
    Learn on your schedule

%p
- if current_user
  %h2
    .fa.fa-user-graduate
    Continue Learning
  .row
    - @purchased_courses.each do |course|
      .card-lg-6.col-md-4.col-12.mt-3
        = render 'courses/course', course: course
  .text-end
    = link_to 'All my purchased courses', purchased_courses_path, class: 'btn btn-primary btn-sm mt-4'
  %hr
%h2
  .fa.fa-chart-line
  Popular courses
.row
  - @popular.each do |course|
    .card-lg-6.col-md-4.col-12.mt-3
      = render 'courses/course', course: course
.text-end
  = link_to 'More popular courses', courses_path(courses_search: {s: 'enrollments_count desc'}), class: 'btn btn-primary btn-sm mt-4'
-# courses_search - for ransack, s for sort by

%hr
%h2
  .fa.fa-star
  Top rated courses
.row
  - @top_rated.each do |course|
    .card-lg-6.col-md-4.col-12.mt-3
      = render 'courses/course', course: course
.text-end
  = link_to 'Best rated courses', courses_path(courses_search: {s: 'average_rating desc'}), class: 'btn btn-primary btn-sm mt-4'

%hr
%h2
  .fa.fa-clock
  Latest courses
.row
  - @latest.each do |course|
    .card-lg-6.col-md-4.col-12.mt-3
      = render 'courses/course', course: course
.text-end
  = link_to 'More new courses', courses_path(courses_search: {s: 'created_at desc'}), class: 'btn btn-primary btn-sm mt-4'

%hr
%h2
  .fa.fa-comment
  What our students have to say
.row
  - @latest_good_reviews.each do |enrollment|
    .card-lg-6.col-md-4.col-12.mt-3
      = render 'enrollments/enrollment', enrollment: enrollment

app/views/home/privacy_policy.html.haml
%h2 Privacy Policy
%p
  Your privacy is important to us. It is Corsego's policy to respect your privacy regarding any information we may collect from you across our website,
  = succeed "," do
    %a{:href => "http://corsego.com"} http://corsego.com
%p We only ask for personal information when we truly need it to provide a service to you. We collect it by fair and lawful means, with your knowledge and consent. We also let you know why we’re collecting it and how it will be used.
%p We only retain collected information for as long as necessary to provide you with your requested service. What data we store, we’ll protect within commercially acceptable means to prevent loss and theft, as well as unauthorized access, disclosure, copying, use or modification.
%p We don’t share any personally identifying information publicly or with third-parties, except when required to by law.
%p Our website may link to external sites that are not operated by us. Please be aware that we have no control over the content and practices of these sites, and cannot accept responsibility or liability for their respective privacy policies.
%p You are free to refuse our request for your personal information, with the understanding that we may be unable to provide you with some of your desired services.
%p Your continued use of our website will be regarded as acceptance of our practices around privacy and personal information. If you have any questions about how we handle user data and personal information, feel free to contact us.
%p This policy is effective as of 31 August 2022.