config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :enrollments do
    get :my_students, on: :collection
  end
  root 'home#index'
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons, except: [:index] do
      resources :comments, except: [:index]
      # put :sort
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: %i[new create]
  end
  resources :users, only: %i[index edit show update]
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
  get 'privacy_policy', to: 'home#privacy_policy'
  resources :youtube, only: :show

  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end
  # get 'charts/users_per_day', to: 'charts#users_per_day'
  # get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  # get 'charts/course_popularity', to: 'charts#course_popularity'
  # get 'charts/money_makers', to: 'charts#money_makers'
end

app/models/enrollment.rb
# frozen_string_literal: true

class Enrollment < ApplicationRecord
  belongs_to :course, counter_cache: true # в момент изменения enrollment, связанное поле enrollments_count будет обновлено
  # Course.find_each { |course| Course.reset_counters(course.id, :enrollments) } Update counter_cache for enrollments count
  belongs_to :user, counter_cache: true
  # User.find_each { |user| User.reset_counters(user.id, :enrollments) }  Update counter_cache

  # если есть рейтинг, то должно быть и review и наоборот
  validates :rating, presence: { if: :review? }
  validates :review, presence: { if: :rating? }

  validates :user_id, uniqueness: { scope: :course_id }  # user cant be subscribed to the same course twice
  validates :course_id, uniqueness: { scope: :user_id }  # user cant be subscribed to the same course twice

  validate :cant_subscribe_to_own_course # user can't create a subscription if course.user == current_user.id

  scope :pending_review, -> { where(rating: [0, nil, ''], review: [0, nil, '']) }
  scope :reviewed, -> { where.not(review: [0, nil, '']) }
  scope :latest_good_reviews, -> { order(rating: :desc, created_at: :desc).limit(3) }

  extend FriendlyId
  friendly_id :to_s, use: :slugged
  def to_s
    "#{user} #{course}"
  end

  after_save do
    course.update_rating unless rating.nil? || rating.zero? # Избегает лишних запросов по обновлению рейтинга
  end

  after_destroy do
    course.update_rating
  end

  protected

  def cant_subscribe_to_own_course
    errors.add(:base, 'You cannot subscribe to your own course') if new_record? && user_id.present? && (user_id == course.user_id)
  end
end

app/controllers/enrollments_controller.rb
# frozen_string_literal: true

class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[show edit update destroy]
  before_action :set_course, only: %i[new create]

  def index
    @ransack_path = enrollments_path # Кастомный путь для использования с ransack
    @q = Enrollment.ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))
    authorize_enrollment!
  end

  def my_students
    @ransack_path = my_students_enrollments_path
    @q = Enrollment.joins(:course).where(courses: {user: current_user}).ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))
    render 'index'
  end

  def show
  end

  def new
    @enrollment = Enrollment.new
  end

  def edit
    authorize_enrollment!
  end

  def create
    if @course.price.positive?
      flash[:alert] = 'You cannot access paid courses yet.'
      redirect_to new_course_enrollment_path(@course)
    else
      @enrollment = current_user.buy_course(@course)
      redirect_to course_path(@course), notice: 'You are enrolled!'
    end
  end

  def update
    authorize_enrollment!
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to enrollment_url(@enrollment), notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize_enrollment!
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_enrollment
    @enrollment = Enrollment.friendly.find(params[:id])
  end

  def set_course
    @course = Course.friendly.find(params[:course_id])
  end

  def authorize_enrollment!
    authorize(@enrollment || Enrollment)
  end

  def enrollment_params
    params.require(:enrollment).permit(:rating, :review)
  end
end

app/views/enrollments/_enrollment.html.haml
.card
  .card-header
    .fa.fa-user
    = link_to enrollment.user.username, user_path(enrollment.user)
    .fa.fa-clock
    = time_ago_in_words(enrollment.updated_at)
    .fa.fa-graduation-cap
    = link_to enrollment.course, course_path(enrollment.course)
  .card-body
    .text-warning.fa.fa-star
    %b= enrollment.rating
    .fa.fa-comment
    %small= enrollment.review
  - if current_user
    .card-footer
      - if policy(enrollment).edit?
        = link_to 'Edit Review', edit_enrollment_path(enrollment)

app/views/enrollments/_form.html.haml
= simple_form_for(@enrollment) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    .col-form-label.pt-0
      = f.input :rating, collection: 1..5, as: :radio_buttons
      = f.input :review

  .form-actions
    = f.button :submit, class: 'mt-3'

app/views/enrollments/edit.html.haml
- content_for :title do
  Corsego
  |
  Review
  = @enrollment.course

.card.shadow
  .card-header
    %h3
      .text-warning.fa.fa-star
      Add a Review
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Show Review', @enrollment
    \|
    = link_to 'Back to course', course_path(@enrollment.course)

app/views/enrollments/index.html.haml
- content_for :title do
  Corsego
  |
  = controller_name.humanize
  = action_name.humanize

%h3
  .text-center
    .fa.fa-lock-open
    = controller_name.humanize + ":"
    = action_name.humanize
    .badge.bg-info
      = @enrollments.count
%p

.card.shadow-sm.mb-3
  .card-body.bg-light
    -# Необходимо добавить кастомный url: @ransack_path для того чтобы перенаправлять на нужный путь,
    -# вместо всех enrollments
    = search_form_for @q, url: @ransack_path do |f|
      = f.search_field :user_email_cont, placeholder: 'user email'
      = f.search_field :course_user_email_cont, placeholder: 'teacher'
      = f.search_field :price_eq, placeholder: 'price'
      = f.search_field :rating_eq, placeholder: 'rating'
      = f.submit
      = link_to url_for, class: 'btn btn-sm btn-secondary' do
        .fa.fa-sync

.table-responsive
  %table.table.table-bordered.table-striped.table-sm
    %thead
      %tr
        -#%th ID
        %th= sort_link(@q, :user_email, "User")
        %th= sort_link(@q, :created_at)
        %th= sort_link(@q, :course_title, "Course")
        %th Teacher
        %th= sort_link(@q, :price)
        %th
          = sort_link(@q, :updated_at)
          .row
          .text-warning.fa.fa-clock
          Reviewed on
        %th
          = sort_link(@q, :rating)
          .text-warning.fa.fa-star
        %th
          .text-warning.fa.fa-comment
          Review
        %th Progress
        %th
        %th
        %th

    %tbody
      - @enrollments.each do |enrollment|
        %tr
          -#%td= enrollment.id
          %td= link_to enrollment.user.email, user_path(enrollment.user)
          %td= enrollment.created_at.strftime("%d/%b/%Y, %H:%M")
          %td= link_to enrollment.course, course_path(enrollment.course)
          %td= link_to enrollment.course.user, user_path(enrollment.course.user)
          %td= number_to_currency(enrollment.price)
          %td
            - if enrollment.rating.present?
              = enrollment.updated_at.strftime("%d/%b/%Y, %H:%M")
          %td= enrollment.rating
          %td= enrollment.review
          %td= number_to_percentage(enrollment.course.progress(enrollment.user), precision: 0)
          %td= link_to 'See Review', enrollment, class: 'btn btn-primary btn-sm'
          %td
            - if policy(enrollment).edit?
              = link_to 'Add Review', edit_enrollment_path(enrollment), class: 'btn btn-primary btn-sm'
          %td
            - if policy(enrollment).destroy?
              = link_to 'Delete Enrollment', enrollment, method: :delete, data: { confirm: 'Are your sure?' }, class: 'btn btn-danger btn-sm'

!= pagy_bootstrap_nav(@pagy)
%br

= link_to 'New Enrollment', new_enrollment_path

app/views/enrollments/new.html.haml
- content_for :title do
  Corsego 
  \| 
  New enrollment

.card
  .card-header
    %h3
      .fa.fa-graduation-cap
      = link_to @course.title, course_path(@course)
      %hr
      .fa.fa-lock-open
      Buy course
  .card-body
    = form_tag course_enrollments_path(@course) do
      = submit_tag "Pay #{@course.price}", class: 'btn btn-lg btn-success'
  .card-footer
    = link_to 'Back', course_path(@course)

app/views/enrollments/show.html.haml
= render 'enrollments/enrollment', enrollment: @enrollment